name = "ppt-paste"
main = "worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# R2 bucket for PPTX file storage
[[r2_buckets]]
binding = "PPTX_STORAGE"
bucket_name = "ppt-paste-files"

# Static assets binding
[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

# KV namespace for rate limiting
[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
preview_id = "9ee2384f43b148e195d957b9cfeff52c"
id = "82eb980701c54b07ada09ec8f2047995"

[env.production]
name = "ppt-paste-worker"

[env.development]
name = "ppt-paste-worker-dev"