name = "ppt-paste"
main = "worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# R2 bucket for PPTX file storage
[[r2_buckets]]
binding = "PPTX_STORAGE"
bucket_name = "ppt-paste-files"

# Static assets binding
[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

# Rate limiting bindings
[[unsafe.bindings]]
name = "UPLOAD_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 10, period = 60 }

[[unsafe.bindings]]
name = "API_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1002"
simple = { limit = 50, period = 60 }

[[unsafe.bindings]]
name = "GLOBAL_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1003"
simple = { limit = 100, period = 60 }

[env.production]
name = "ppt-paste-worker"

[env.development]
name = "ppt-paste-worker-dev"